spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw15
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.changelog