spring:
  batch:
    job:
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw14
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.changeloga