spring:
  data:
    mongodb:
      host: ${mongo_host}
      port: ${mongo_port}
      database: ${mongo_db}
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.changelog
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
      external-file: /logs/server.log
    loggers:
      enabled: true
  health:
    defaults:
      enabled: true
logging:
  file:
    name: logs/server.log