spring:
  data:
    rest:
      base-path: /api
    mongodb:
      host: localhost
      port: 27017
      database: hw08
  mongock:
    change-logs-scan-package:
      - ru.otus.changelog
    runner-type: initializingbean
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
