version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - WAIT_HOSTS:mongo-db:27017
      - mongo_host=mongo-db
      - mongo_port=27017
      - mongo_db=hw17
  mongo-db:
    image: mongo
    ports:
      - 27017:27017